name: Test ADAM with conda-forge dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build-with-conda-forge-dependencies:
    name: '[conda-forge:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Print used environment (no conda) [Conda]
      shell: bash
      run: |
        env
    - name: Get current week
      id: week
      run: echo "week=$(date +%Y-%U)" >> "${GITHUB_OUTPUT}"
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ci_env.yml
        cache-environment-key: environment-${{ steps.week.outputs.week }}

    - name: Install ADAM
      shell: bash -l {0}
      run: |
          pip install --no-deps .

    - name: Test with pytest
      shell: bash -l {0}
      run: |
          pytest

