name: Test ADAM with conda-forge dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build-with-conda-forge-dependencies:
    name: '[conda-forge:${{ matrix.os }}:${{ matrix.docker_image }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-latest]
        docker_image:
          - "quay.io/condaforge/linux-anvil-cos7-x86_64"
          - "centos:7"
          - "fedora:26" 
          - "fedora:27"
          - "ubuntu:16.04"
          - "ubuntu:18.04"
          - "ubuntu:20.04"
          - "ubuntu:22.04"
    container:
      image: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment [CentOS/Fedora]
      shell: bash -l {0}
      if: contains(matrix.docker_image, 'cos7') || contains(matrix.docker_image, 'centos') || contains(matrix.docker_image, 'fedora')
      run: |
          # conda-forge's iDynTree requires GL.so at runtime
          yum install -y mesa-libGL libselinux libXdamage libXxf86vm libXext

    - name: Setup environment [Debian-based]
      shell: bash -l {0}
      if: contains(matrix.docker_image, 'ubuntu')
      run: |
          # mamba requires ca-certificats
          # conda-forge's iDynTree requires GL.so at runtime
          apt-get update -y
          apt-get install -y bzip2 ca-certificates curl libgl1

    - name: Get current week
      id: week
      run: echo "week=$(date +%Y-%U)" >> "${GITHUB_OUTPUT}"
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ci_env.yml
        cache-environment-key: environment-${{ steps.week.outputs.week }}-${{ matrix.docker_image }}
        
    - name: Print packages and environment
      shell: bash -l {0}
      run: |
        env
        micromamba list

    - name: Install ADAM
      shell: bash -l {0}
      run: |
          # conda-forge's iDynTree requires GL.so at runtime
          yum install -y mesa-libGL libselinux libXdamage libXxf86vm libXext
          # SETUPTOOLS_SCM_PRETEND_VERSION used as a workaround for 
          # https://github.com/pypa/setuptools_scm#usage-from-docker
          SETUPTOOLS_SCM_PRETEND_VERSION=1 pip install --no-deps .

    - name: Test with pytest
      shell: bash -l {0}
      run: |
          pytest

